---
  - name: deploy tomcat8 based application gol
    hosts: all
    become: yes
    tasks:
     - name: update ubuntu packages and install openjdk
       apt: 
        name: openjdk-8-jdk
        update_cache: yes
        state: present
     - name:  install tomcat
       apt: 
        name: tomcat8
        state: present   
     - name: download gol
       get_url:
         url: https://referenceappkhaja.s3-us-west-2.amazonaws.com/gameoflife.war
         dest: /var/lib/tomcat8/webapps/gameoflife.war 