---
- name: deploy tomcat8 based application game of life
  become: yes
  hosts: all
  tasks:
    - name: update ubuntu packages and install java
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: install tomcat8
      apt: 
        name: tomcat8
        state: present
    - name: Download game of life
      get_url:
        url: 'http://search.maven.org/remotecontent?filepath=org/kill-bill/billing/killbill-profiles-killbill/0.12.1/killbill-profiles-killbill-0.12.1.war'

        dest: /var/lib/tomcat8/webapps/gameoflife.war